data:
    train_filename: '200_samples_1672_classes'

model:
    arch: 'resnet50'
    num_classes: 1672

train:
    images_per_class: 200
    use_balancing_sampler: true

val:
    images_per_class: 10

optimizer:
    name: 'adam'
    params:
        lr: 0.0003

scheduler:
    name: 'reduce_lr_on_plateau'

loss:
    name: 'cross_entropy'
