data:
    train_filename: '50_samples_18425_classes'

model:
    arch: 'resnet50'
    num_classes: 18425

train:
    images_per_class: 50
    max_steps_per_epoch: 15000

val:
    images_per_class: 3

optimizer:
    name: 'sgd'
    params:
        lr: 0.001

scheduler:
    name: 'reduce_lr_on_plateau'

loss:
    name: 'cross_entropy'
